name: Check Ansible Debian stable
description: Check ansible role or playbook with the debian:stable docker container
author: L3D <l3d@c3woc.de>

inputs: 
  targets:
    description: |
      Paths to the ansible role or playbook you want to be tested.
      For example './', 'roles/my_role/' or 'site.yml'
    required: true
runs:
  using: docker
  image: Dockerfile
  env:
    TARGETS: ${{ inputs.targets }}
branding:
  icon: 'aperture' 
  color: 'green'
